### ISSUE TITLE
librabbitmq-c 0.8.0 compilation error

### ISSUE THREAD

**Issue by frol** [jbg/rabbitmq#2]
It seems that there is a compatibility issue with the latest librabbitmq-c (0.8.0 released in April). Once I try to `import rabbitmq` I get the following error:

```
env/lib/python3.6/site-packages/rabbitmq/__pycache__/_cffi__xb855cecexf09c1d86.c: In function ‘_cffi_f_amqp_exchange_declare’:
env/lib/python3.6/site-packages/rabbitmq/__pycache__/_cffi__xb855cecexf09c1d86.c:1294:60: error: incompatible type for argument 7 of ‘amqp_exchange_declare’
   { result = amqp_exchange_declare(x0, x1, x2, x3, x4, x5, x6); }
                                                            ^~
In file included from /usr/include/amqp.h:765:0,
                 from env/lib/python3.6/site-packages/rabbitmq/__pycache__/_cffi__xb855cecexf09c1d86.c:209:
/usr/include/amqp_framing.h:798:11: note: expected ‘amqp_boolean_t {aka int}’ but argument is of type ‘amqp_table_t {aka struct amqp_table_t_}’
 AMQP_CALL amqp_exchange_declare(amqp_connection_state_t state, amqp_channel_t channel, amqp_bytes_t exchange, amqp_bytes_t type, amqp_boolean_t passive, amqp_boolean_t durable, amqp_boolean_t auto_delete, amqp_boolean_t internal, amqp_table_t arguments);
           ^~~~~~~~~~~~~~~~~~~~~
env/lib/python3.6/site-packages/rabbitmq/__pycache__/_cffi__xb855cecexf09c1d86.c:1294:14: error: too few arguments to function ‘amqp_exchange_declare’
   { result = amqp_exchange_declare(x0, x1, x2, x3, x4, x5, x6); }
              ^~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/amqp.h:765:0,
                 from env/lib/python3.6/site-packages/rabbitmq/__pycache__/_cffi__xb855cecexf09c1d86.c:209:
/usr/include/amqp_framing.h:798:11: note: declared here
 AMQP_CALL amqp_exchange_declare(amqp_connection_state_t state, amqp_channel_t channel, amqp_bytes_t exchange, amqp_bytes_t type, amqp_boolean_t passive, amqp_boolean_t durable, amqp_boolean_t auto_delete, amqp_boolean_t internal, amqp_table_t arguments);
           ^~~~~~~~~~~~~~~~~~~~~
Traceback (most recent call last):
  File "/usr/lib64/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/usr/lib64/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib64/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib64/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/env/lib/python3.6/site-packages/cffi/ffiplatform.py", line 49, in _build
    dist.run_command('build_ext')
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/usr/lib64/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib64/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "qq2.py", line 1, in <module>
    import rabbitmq
  File "/tmp/env/lib/python3.6/site-packages/rabbitmq/__init__.py", line 248, in <module>
    """, libraries=["rabbitmq"])
  File "/tmp/env/lib/python3.6/site-packages/cffi/api.py", line 438, in verify
    lib = self.verifier.load_library()
  File "/tmp/env/lib/python3.6/site-packages/cffi/verifier.py", line 114, in load_library
    self._compile_module()
  File "/tmp/env/lib/python3.6/site-packages/cffi/verifier.py", line 211, in _compile_module
    outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
  File "/tmp/env/lib/python3.6/site-packages/cffi/ffiplatform.py", line 20, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/tmp/env/lib/python3.6/site-packages/cffi/ffiplatform.py", line 56, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1
```

My system:

* Arch Linux
* Python 3.6
* librabbitmq-c 0.8.0

**Comment by jbg** [comment]
Thanks for the report! I'll take a look into this and release an update for compatibility with the latest librabbitmq.

**Comment by jbg** [comment]
This should be resolved in 0.2.0 released just now, but I will leave this issue open until I've added some tests and set up CI.

**Comment by frol** [comment]
@jbg Awesome! Thank you!!!
